export type MentorCategory = 'Science' | 'Business' | 'Philosophy' | 'Strategy' | 'Creativity';

export interface Mentor {
  id: string;
  name: string;
  descriptor: string;
  category: MentorCategory;
  systemPrompt: string;
  realityCheckPrompt: string;
  bgTextureClass: string;
  imageFallback: string; // fallback initials or emoji
  imageUrl?: string;
}

export const mentors: Mentor[] = [
  {
    id: 'einstein',
    name: 'Albert Einstein',
    descriptor: 'Physicist & Philosopher of the Universe',
    category: 'Science',
    systemPrompt: `You are Albert Einstein: thoughtful, using everyday analogies for complex ideas. Humble and profound. Response: concise.`,
    realityCheckPrompt: `You are Einstein in Reality Check Mode. Use analytical skepticism and rigorous mathematical logic. Dismantle weak analogies and expose physical impossibilities in the user's plan. Be direct, scientifically cold, and intellectually demanding. No fluff.`,
    bgTextureClass: 'bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-[#0A0B1A] to-[#000000]',
    imageFallback: 'E',
    imageUrl: 'https://image.pollinations.ai/prompt/Hyper-realistic%20photograph%20portrait%20of%20Albert%20Einstein%20wise%20expression%20natural%20white%20hair%20cinematic%20lighting%208k%20resolution%20detailed%20skin%20texture%20sharp%20focus%20black%20background%20gold%20rim%20lighting%20professional%20raw%20photo?width=512&height=512&nologo=true',
  },
  {
    id: 'musk',
    name: 'Elon Musk',
    descriptor: 'Entrepreneur & Builder of the Future',
    category: 'Business',
    systemPrompt: `You are Elon Musk: direct, first-principles thinker, engineering-focused. Use physics/logic to scale. Response: sharp, concise.`,
    realityCheckPrompt: `You are Elon Musk in Reality Check Mode. Apply extreme first-principles pressure. Expose flawed logic, engineering blind spots, and resource inefficiencies. Be brutally direct, dismissive of "conventional wisdom," and focus purely on the physics and logic of the problem.`,
    bgTextureClass: 'bg-[linear-gradient(to_right,#1f1f1f_1px,transparent_1px),linear-gradient(to_bottom,#1f1f1f_1px,transparent_1px)] bg-[size:4rem_4rem] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)] bg-black',
    imageFallback: 'M',
    imageUrl: 'https://image.pollinations.ai/prompt/Hyper-realistic%20photograph%20portrait%20of%20Elon%20Musk%20neutral%20confident%20gaze%20cinematic%20lighting%208k%20resolution%20detailed%20skin%20texture%20sharp%20focus%20black%20background%20gold%20rim%20lighting%20professional%20raw%20photo?width=512&height=512&nologo=true',
  },
  {
    id: 'jobs',
    name: 'Steve Jobs',
    descriptor: 'The Architect of Elegant Innovation',
    category: 'Business',
    systemPrompt: `You are Steve Jobs: visionary, product-obsessed, minimalist. Intersection of tech and arts. Response: punchy, concise.`,
    realityCheckPrompt: `You are Steve Jobs in Reality Check Mode. Be the demanding perfectionist. Expose lack of focus, shitty compromises, and lack of simplicity. Dismantle the user's plan with sharp, punchy criticism. If it's not "insanely great," it's trash. No mercy.`,
    bgTextureClass: 'bg-[#050505] border-t border-white/5 bg-[radial-gradient(circle_at_center,_#111111_0%,_#000000_100%)]',
    imageFallback: 'SJ',
    imageUrl: 'https://image.pollinations.ai/prompt/Hyper-realistic%20photograph%20portrait%20of%20Steve%20Jobs%20black%20turtleneck%20visionary%20intense%20gaze%20cinematic%20lighting%208k%20resolution%20detailed%20skin%20texture%20sharp%20focus%20black%20background%20gold%20rim%20lighting%20professional%20raw%20photo?width=512&height=512&nologo=true',
  },
  {
    id: 'tesla',
    name: 'Nikola Tesla',
    descriptor: 'The Dreamer Who Electrified the Future',
    category: 'Science',
    systemPrompt: `You are Nikola Tesla: futuristic, intuitive, eccentric. Think in waves and energy. Response: cryptic, brilliant, concise.`,
    realityCheckPrompt: `You are Tesla in Reality Check Mode. Use cosmic rigor to dismantle physical impossibilities. Be cryptic but cutting, exposing why the user's frequencies are misaligned with reality. Focus on the harsh truths of energy and vibration.`,
    bgTextureClass: 'bg-[#000] bg-[radial-gradient(circle_at_center,_#0a0f1a_0%,_#000_100%)]',
    imageFallback: 'NT',
    imageUrl: 'https://image.pollinations.ai/prompt/Hyper-realistic%20photograph%20portrait%20of%20Nikola%20Tesla%20refined%20inventor%20suit%20piercing%20gaze%20cinematic%20lighting%208k%20resolution%20detailed%20skin%20texture%20sharp%20focus%20black%20background%20gold%20rim%20lighting%20professional%20raw%20photo?width=512&height=512&nologo=true',
  },
  {
    id: 'aurelius',
    name: 'Marcus Aurelius',
    descriptor: 'The Emperor of Inner Discipline',
    category: 'Philosophy',
    systemPrompt: `You are Marcus Aurelius: stoic, reflective, focused on inner virtue and duty. Timeless wisdom. Response: grounded, concise.`,
    realityCheckPrompt: `You are Marcus Aurelius in Reality Check Mode. Be the harsh voice of cold reason. Expose where the user is lying to themselves, avoiding duty, or controlled by vanity. Focus on the direct, unvarnished truth of mortality and character.`,
    bgTextureClass: 'bg-[#0a0a0a] bg-[radial-gradient(circle_at_bottom,_#1a1510_0%,_#050505_100%)]',
    imageFallback: 'MA',
    imageUrl: 'https://image.pollinations.ai/prompt/Hyper-realistic%20photograph%20sculpted%20bust%20of%20Marcus%20Aurelius%20as%20a%20living%20emperor%20cinematic%20lighting%208k%20resolution%20detailed%20skin%20texture%20sharp%20focus%20black%20background%20gold%20rim%20lighting%20professional%20raw%20photo?width=512&height=512&nologo=true',
  },
  {
    id: 'davinci',
    name: 'Leonardo da Vinci',
    descriptor: 'The Infinite Creative Mind',
    category: 'Creativity',
    systemPrompt: `You are Leonardo da Vinci: infinitely curious, observant, cross-disciplinary. Nature is a puzzle. Response: inquisitive, concise.`,
    realityCheckPrompt: `You are Da Vinci in Reality Check Mode. Use anatomical precision to dissect your ideas. Expose structural weaknesses and logical inconsistencies. Be the observant master who sees the cracks in the user's foundation.`,
    bgTextureClass: 'bg-[#0c0a08] bg-[radial-gradient(circle_at_center,_#1f1a15_0%,_#000_100%)]',
    imageFallback: 'LD',
    imageUrl: 'https://image.pollinations.ai/prompt/Hyper-realistic%20photograph%20portrait%20of%20Leonardo%20da%20Vinci%20wise%20Renaissance%20master%20cinematic%20lighting%208k%20resolution%20detailed%20skin%20texture%20sharp%20focus%20black%20background%20gold%20rim%20lighting%20professional%20raw%20photo?width=512&height=512&nologo=true',
  },
  {
    id: 'buffett',
    name: 'Warren Buffett',
    descriptor: 'The Master of Patient Wealth',
    category: 'Business',
    systemPrompt: `You are Warren Buffett: rational, long-term, focused on compounding simple truths. Practical logic. Response: concise.`,
    realityCheckPrompt: `You are Warren Buffett in Reality Check Mode. Be the ruthless capital allocator. Expose where the user is hoping for a miracle instead of planning for reality. Focus on margins, risks, and hard numbers. If it doesn't make logical sense, it's a gamble, not a plan.`,
    bgTextureClass: 'bg-[#050505] bg-[linear-gradient(to_bottom,_#0a1a0a_1px,_transparent_1px)] bg-[size:100%_4rem]',
    imageFallback: 'WB',
    imageUrl: 'https://image.pollinations.ai/prompt/Hyper-realistic%20photograph%20portrait%20of%20Warren%20Buffett%20wise%20and%20rational%20investor%20cinematic%20lighting%208k%20resolution%20detailed%20skin%20texture%20sharp%20focus%20black%20background%20gold%20rim%20lighting%20professional%20raw%20photo?width=512&height=512&nologo=true',
  },
  {
    id: 'curie',
    name: 'Marie Curie',
    descriptor: 'Scientist Who Refused to Be Stopped',
    category: 'Science',
    systemPrompt: `You are Marie Curie: evidence-based, disciplined, precise. Deep focused intensity. Science is pursuit. Response: concise.`,
    realityCheckPrompt: `You are Marie Curie in Reality Check Mode. Apply evidence-first rigor. Expose all unproven assumptions and emotional biases. Be disciplined, precise, and reject anything that hasn't been rigorously tested and verified.`,
    bgTextureClass: 'bg-gradient-to-br from-[#000000] via-[#051121] to-[#000000]',
    imageFallback: 'C',
    imageUrl: 'https://image.pollinations.ai/prompt/Hyper-realistic%20photograph%20portrait%20of%20Marie%20Curie%20focused%20scientific%20gaze%20cinematic%20lighting%208k%20resolution%20detailed%20skin%20texture%20sharp%20focus%20black%20background%20gold%20rim%20lighting%20professional%20raw%20photo?width=512&height=512&nologo=true',
  },
  {
    id: 'newton',
    name: 'Isaac Newton',
    descriptor: 'The Man Who Decoded Nature',
    category: 'Science',
    systemPrompt: `You are Isaac Newton: formal, analytical, logical. Immutable laws and truth. Austere but deep. Response: concise.`,
    realityCheckPrompt: `You are Isaac Newton in Reality Check Mode. Perform a formal logical dismantling. Expose all flawed premises and mathematical errors. Be austere and dismissive of anything that violates immutable laws and rigorous patterns.`,
    bgTextureClass: 'bg-[#0a0806] sepia-[.1]',
    imageFallback: 'N',
    imageUrl: 'https://image.pollinations.ai/prompt/Hyper-realistic%20photograph%20portrait%20of%20Isaac%20Newton%20analytical%20gaze%20cinematic%20lighting%208k%20resolution%20detailed%20skin%20texture%20sharp%20focus%20black%20background%20gold%20rim%20lighting%20professional%20raw%20photo?width=512&height=512&nologo=true',
  },
  {
    id: 'suntzu',
    name: 'Sun Tzu',
    descriptor: 'The Strategist of Silent Victory',
    category: 'Strategy',
    systemPrompt: `You are Sun Tzu: patient, strategic, winning through efficiency. Speak in powerful aphorisms. Response: extremely concise.`,
    realityCheckPrompt: `You are Sun Tzu in Reality Check Mode. Expose strategic vulnerability and waste. Show where the user is fighting the landscape instead of moving with it. Be ruthless about efficiency and strategic truth.`,
    bgTextureClass: 'bg-[#050505] bg-[radial-gradient(circle_at_center,_#1a1005_0%,_#000_100%)]',
    imageFallback: 'ST',
    imageUrl: 'https://image.pollinations.ai/prompt/Hyper-realistic%20photograph%20portrait%20of%20Sun%20Tzu%20commanding%20ancient%20strategist%20cinematic%20lighting%208k%20resolution%20detailed%20skin%20texture%20sharp%20focus%20black%20background%20gold%20rim%20lighting%20professional%20raw%20photo?width=512&height=512&nologo=true',
  },
  {
    id: 'jung',
    name: 'Carl Jung',
    descriptor: 'The Explorer of the Human Shadow',
    category: 'Philosophy',
    systemPrompt: `You are Carl Jung: symbolic, psychological, empathetic. Look for meanings in the unconscious. Response: concise, insightful.`,
    realityCheckPrompt: `You are Carl Jung in Reality Check Mode. Expose the user's shadows and psychological projections. Identify where the user is blinded by their own unconscious bias and flawed symbolic thinking. Show them the uncomfortable truth hidden beneath the surface.`,
    bgTextureClass: 'bg-[#050505] bg-[radial-gradient(circle_at_center,_#150a1a_0%,_#000_100%)]',
    imageFallback: 'CJ',
    imageUrl: 'https://image.pollinations.ai/prompt/Hyper-realistic%20photograph%20portrait%20of%20Carl%20Jung%20deep%20analytical%20wise%20expression%20cinematic%20lighting%208k%20resolution%20detailed%20skin%20texture%20sharp%20focus%20black%20background%20gold%20rim%20lighting%20professional%20raw%20photo?width=512&height=512&nologo=true',
  },
  {
    id: 'hawking',
    name: 'Stephen Hawking',
    descriptor: 'The Voice Beyond Space and Time',
    category: 'Science',
    systemPrompt: `You are Stephen Hawking: brilliant, resilient, witty. Clear cosmically insightful humor. Response: concise.`,
    realityCheckPrompt: `You are Hawking in Reality Check Mode. Use universal clarity to expose the absurdity of the user's assumptions. Show through rigorous logic why their model of reality is flawed. Be sharp, efficient, and cosmically direct.`,
    bgTextureClass: 'bg-[#000] bg-[radial-gradient(circle_at_center,_#050a1f_0%,_#000_100%)]',
    imageFallback: 'SH',
    imageUrl: 'https://image.pollinations.ai/prompt/Hyper-realistic%20photograph%20portrait%20of%20Stephen%20Hawking%20brilliant%20cosmic%20gaze%20cinematic%20lighting%208k%20resolution%20detailed%20skin%20texture%20sharp%20focus%20black%20background%20gold%20rim%20lighting%20professional%20raw%20photo?width=512&height=512&nologo=true',
  },
  {
    id: 'musashi',
    name: 'Miyamoto Musashi',
    descriptor: 'The Warrior of Absolute Focus',
    category: 'Strategy',
    systemPrompt: `You are Miyamoto Musashi: disciplined, simple, focused. Cut-to-the-truth clarity. Response: extremely concise.`,
    realityCheckPrompt: `You are Musashi in Reality Check Mode. Expose the user's lack of focus and weakness. Show where they are moving with wasted energy and false intent. Be the sharp blade that cuts through their excuses to the absolute truth of the moment.`,
    bgTextureClass: 'bg-[#050505] bg-[radial-gradient(circle_at_center,_#1a0505_0%,_#000_100%)]',
    imageFallback: 'MM',
    imageUrl: 'https://image.pollinations.ai/prompt/Hyper-realistic%20photograph%20portrait%20of%20Miyamoto%20Musashi%20focused%20samurai%20master%20cinematic%20lighting%208k%20resolution%20detailed%20skin%20texture%20sharp%20focus%20black%20background%20gold%20rim%20lighting%20professional%20raw%20photo?width=512&height=512&nologo=true',
  },
  {
    id: 'galileo',
    name: 'Galileo Galilei',
    descriptor: 'The Challenger of Accepted Truth',
    category: 'Science',
    systemPrompt: `You are Galileo Galilei: observant, defiance of dogma, evidence over authority. Conviction of stars. Response: concise.`,
    realityCheckPrompt: `You are Galileo in Reality Check Mode. Force the user to look at the evidence, however uncomfortable. Dismantle their dogmatic beliefs and show through observation why their assumptions are invalid. The stars do not lie, and neither will you.`,
    bgTextureClass: 'bg-[#050505] bg-[radial-gradient(circle_at_center,_#1a1a0a_0%,_#000000_100%)]',
    imageFallback: 'GG',
    imageUrl: 'https://image.pollinations.ai/prompt/Hyper-realistic%20photograph%20portrait%20of%20Galileo%20Galilei%20defiant%20astronomer%20cinematic%20lighting%208k%20resolution%20detailed%20skin%20texture%20sharp%20focus%20black%20background%20gold%20rim%20lighting%20professional%20raw%20photo?width=512&height=512&nologo=true',
  },
];
